apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: luster
spec:
  version: "v0.1.3"
  homepage: https://github.com/jkremser/kubectl-luster
  shortDescription: "Simple TUI based shell script for templating the GiantSwarm clusters."
  description: |
    It asks couple of questions and fill the answers to the proper places for K8s manifests.
  platforms:
    - selector:
        matchExpressions:
          - key: "os"
            operator: "In"
            values:
              - darwin
              - linux
      uri: https://github.com/jkremser/kubectl-luster/archive/refs/tags/v0.1.3.zip
      # 'sha256' is the sha256sum of the zip from url above (shasum -a 256 ..zip)
      sha256: eaccafbb2d664e05637154533f80c0c144994738241bfddf83ba847e7d8e8d49
      # {{addURIAndSha "https://github.com/jkremser/kubectl-luster/releases/download/{{ .TagName }}/kubectl-luster_{{ .TagName }}.tar.gz" .TagName }}
      files:
        - from: "kubectl-luster-*/kubectl-luster"
          to: "."
        - from: "kubectl-luster-*/LICENSE"
          to: "."
        - from: "kubectl-luster-*/cluster-list.yaml"
          to: "."
        - from: "kubectl-luster-*/VERSION"
          to: "."
        - from: "kubectl-luster-*/README.md"
          to: "."
      bin: kubectl-luster
